import {RECEIVE_HEADCATES,
         RECEIVE_FOCUSLIST,
         RECEIVE_TAGLIST,
         RECEIVE_NEWITEMLIST,
         RECEIVE_POPULARITEMLIST,
         RECEIVE_FLASHSALEINDEXVO,
         RECEIVE_TOPICLIST,
         RECEIVE_TCATELIST,
         RECEIVE_BANNER,
         RECEIVE_COLUMN,
         RECEIVE_RECOMMEND,
         RECEIVE_TENFIFTEEN,
         RECEIVE_YXLOOK,
         RECEIVE_CATEGORYDATA,
         RECEIVE_REQFINDMORE
} from './mutation-types'
export default{
  [RECEIVE_HEADCATES](state,{headCates}){
    state.headCates=headCates
  },
  [RECEIVE_FOCUSLIST](state,{focusList}){
    state.focusList=focusList
  },
  [RECEIVE_TAGLIST](state,{tagList}){
    state.tagList=tagList
  },
  [RECEIVE_NEWITEMLIST](state,{newItemList}){
    state.newItemList=newItemList
  },
  [RECEIVE_POPULARITEMLIST](state,{popularItemList}){
    state.popularItemList=popularItemList
  },
  [RECEIVE_FLASHSALEINDEXVO](state,{flashSaleIndexVO}){
    state.flashSaleIndexVO=flashSaleIndexVO
  },
  [RECEIVE_TOPICLIST](state,{topicList}){
    state.topicList=topicList
  },
  [RECEIVE_TCATELIST](state,{tcateList}){
    state.tcateList=tcateList
  },
  //识物轮播
  [RECEIVE_BANNER](state,{banner}){
    state.banner=banner
  },
  //严选推荐
  [RECEIVE_COLUMN](state,{column}){
    state.column=column
  },
  //为你推荐
  [RECEIVE_RECOMMEND](state,{recommend}){
    state.recommend=recommend
  },
  //十点一刻
  [RECEIVE_TENFIFTEEN](state,{tenfifteen}){
    state.tenfifteen=tenfifteen
  },
  //严选look
  [RECEIVE_YXLOOK](state,{yxLook}){
    state.yxLook=yxLook
  },
  //分类
  [RECEIVE_CATEGORYDATA](state,{categoryData}){
    state.categoryData=categoryData
  },
  //更多精彩
  [RECEIVE_REQFINDMORE](state,{findMore}){
    state.findMore=findMore
  }
}

